#!/bin/bash
if [ -z "$GITLAB_HOST" ]; then
	echo "Error: GITLAB_HOST is not set. Exiting."
	exit 1
fi
DIR=$(dirname "$0")
REPOS=$(source "$DIR/gl-repo-ls-path" | gum filter --no-limit)
TO=$1

if  [ -n "$REPOS" -a -z "$TO" ]; then
    TO="$(gum file --directory $1)/"
fi
cd $TO
while IFS= read -r REPO; do
    if  [ -n "$REPO" -a  -n "$TO"  ]; then
        mkdir -p $REPO
        REPO_SSH="ssh://git@$GITLAB_HOST:2226/$REPO.git"
        gum confirm "git clone $REPO $TO" && git clone $REPO_SSH $REPO
    fi
done <<< "$REPOS"



